### ISSUE TITLE
Move i18n to the frontend

### ISSUE THREAD

**Issue by brouberol** [brouberol/5esheets#41]

**Comment by brouberol** [comment]
@etnbrd how does this work atm? Is everything in French or do we choose English/French based on the `Accept` header?

**Comment by etnbrd** [comment]
Everything in french, for now. We need to add the English traductions, and wire in some language toggle, either based on the `Accept-language` header, or with a manual selection in the UI.

**Comment by brouberol** [comment]
Superb
